# Generated by Django 3.0.5 on 2021-08-13 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='store',
            options={'verbose_name': '店舗情報', 'verbose_name_plural': '店舗情報'},
        ),
        migrations.AddField(
            model_name='store',
            name='store_telnum',
            field=models.IntegerField(null=True),
        ),
    ]
