# Generated by Django 3.0.5 on 2021-08-13 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210813_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='store_telnum',
            field=models.IntegerField(null=True, verbose_name='電話番号'),
        ),
    ]
