# Generated by Django 3.2.6 on 2022-02-12 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class_1_Menu',
            fields=[
                ('class_1_primary_id', models.AutoField(primary_key=True, serialize=False)),
                ('class_1_secondary_id', models.IntegerField()),
                ('class_1_name', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Class_2_Menu',
            fields=[
                ('class_2_primary_id', models.AutoField(primary_key=True, serialize=False)),
                ('class_2_secondary_id', models.IntegerField()),
                ('class_2_name', models.CharField(max_length=16)),
                ('class_1_menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grandmenu_spa.class_1_menu')),
            ],
        ),
        migrations.CreateModel(
            name='Class_3_Menu',
            fields=[
                ('class_3_primary_id', models.AutoField(primary_key=True, serialize=False)),
                ('class_3_secondary_id', models.IntegerField()),
                ('class_3_neme', models.CharField(max_length=16)),
                ('class_3_price', models.CharField(max_length=8)),
                ('class_4_has', models.BooleanField()),
                ('class_3_takeout', models.BooleanField()),
                ('class_2_menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grandmenu_spa.class_2_menu')),
            ],
        ),
        migrations.CreateModel(
            name='Class_4_Menu',
            fields=[
                ('class_4_primary_id', models.AutoField(primary_key=True, serialize=False)),
                ('class_4_secondary_id', models.IntegerField()),
                ('class_4_name', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('store_id', models.AutoField(primary_key=True, serialize=False)),
                ('store_name', models.CharField(max_length=255)),
                ('seating_capacity', models.IntegerField(default=1)),
                ('takeout_support', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('staff_primary_id', models.AutoField(primary_key=True, serialize=False)),
                ('staff_secondary_id', models.IntegerField()),
                ('staff_name', models.CharField(max_length=255)),
                ('e_mail', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('staff_class_id', models.IntegerField(default=1)),
                ('staff_class', models.CharField(default='staff', max_length=32)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grandmenu_spa.store')),
            ],
        ),
        migrations.CreateModel(
            name='Class_5_Menu',
            fields=[
                ('class_5_primary_id', models.AutoField(primary_key=True, serialize=False)),
                ('class_5_secondary_id', models.IntegerField()),
                ('class_5_name', models.CharField(max_length=16)),
                ('class_5_price', models.IntegerField(default=0)),
                ('class_4_menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grandmenu_spa.class_4_menu')),
            ],
        ),
        migrations.CreateModel(
            name='Class_3_to_Class_4',
            fields=[
                ('class_3_class_4_id_primary_id', models.AutoField(primary_key=True, serialize=False)),
                ('class_3_class_4_id_secondary_id', models.IntegerField()),
                ('class_3_menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grandmenu_spa.class_3_menu')),
                ('class_4_menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grandmenu_spa.class_4_menu')),
            ],
        ),
        migrations.AddField(
            model_name='class_2_menu',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grandmenu_spa.store'),
        ),
    ]
